# Generated by Django 4.1.2 on 2022-10-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
