# Generated by Django 4.1.2 on 2022-10-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0018_remove_project_comments_publiccomment_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completion_year',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='starting_year',
            field=models.DateField(null=True),
        ),
    ]
