# Generated by Django 4.1.2 on 2022-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0020_rename_completion_year_project_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmember',
            name='access_token',
            field=models.SlugField(auto_created=True, blank=True, default='4jtz8ZS9jUBc2LF6AlMkum1ByTAz8Lhk', null=True, unique=True),
        ),
    ]
