# Generated by Django 4.1.2 on 2022-10-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0021_cabinetmember_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetmember',
            name='access_token',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
