# Generated by Django 4.1.2 on 2022-10-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0024_alter_cabinetmember_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetmember',
            name='access_token',
        ),
    ]
