# Generated by Django 4.1.2 on 2022-10-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0025_remove_cabinetmember_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmember',
            name='access_token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
