# Generated by Django 4.1.2 on 2022-10-30 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0026_cabinetmember_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetmember',
            name='access_token',
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.cabinetmember')),
            ],
        ),
    ]
