# Generated by Django 4.1.2 on 2022-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0027_remove_cabinetmember_access_token_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmember',
            name='access',
            field=models.CharField(blank=True, default='1EQ341Z5NAIBZ3', editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
