# Generated by Django 4.1.2 on 2022-10-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0028_cabinetmember_access_delete_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinetmember',
            name='access',
            field=models.CharField(blank=True, default='IRMT8XD3OQQ9WY', editable=False, max_length=15, null=True),
        ),
    ]
