# Generated by Django 4.1.2 on 2022-10-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0029_alter_cabinetmember_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabinetmember',
            name='access',
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, default='CX6J2UQ281UEG2', max_length=15, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.cabinetmember')),
            ],
        ),
    ]
