# Generated by Django 4.1.2 on 2022-10-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0030_remove_cabinetmember_access_accesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
