# Generated by Django 4.1.2 on 2022-10-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0031_delete_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinetmember',
            name='access_token',
            field=models.CharField(blank=True, default='JK8X6M1NYWRJPU', editable=False, max_length=15, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='cabinetmember',
            constraint=models.UniqueConstraint(fields=('id', 'access_token'), name='unique cabinetmember'),
        ),
        migrations.AlterModelTable(
            name='cabinetmember',
            table='cabinetmember',
        ),
    ]
