# Generated by Django 4.1.2 on 2022-10-30 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operations', '0033_remove_cabinetmember_unique cabinetmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemovedCabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('office_contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.cabinetposition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ctivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('activity_type', models.CharField(choices=[('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.project')), ('BudgetAllocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.budgetallocation')), ('Government Promisses', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.promissedduty')), ('Removed Cabinet Member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Operations.removedcabinetmember'))], max_length=225, null=True)),
                ('activity', models.CharField(max_length=225)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Operations.publicsector')),
            ],
        ),
    ]
