# Generated by Django 4.1.2 on 2022-10-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Operations', '0034_removedcabinetmember_ctivity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ctivity',
            new_name='Activity',
        ),
    ]
